# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07be1f63673eb103faab65bc0f84774716c4e58784eace6fd082a202c8ee21730f74f6f6e3ddb894cc8bf73ca7a55481b09550a6debcceeeddb4c65ed49247cd

test:
  secret_key_base: 132e6ca47ce3569aed3bc9eec3f59498e076b58174d152565e92b68b38a166950cf5f159a848cc8cd8d09da0de33f7bb695372bdfa886fcf0e5124aa320fc398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
